# Site settings
title: Hern치n Aguilera
email: contacto[at]hernanaguilera[dot]com[dot]ve
description: > # this means to ignore newlines until "baseurl:"
  Sitio para la publicaci칩n y documentaci칩n de mis desvarios en c칩digo fuente.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "" # the base hostname & protocol for your site
twitter_username: HernanAguilera
github_username:  HernanAguilera

highlighter: pygments
# Build settings
markdown: kramdown
